dist: bionic
services:
  - xvfb
language: rust
matrix:
  include:
    - os: linux
      rust: nightly
    - os: linux
      rust: beta
    - os: linux
      rust: stable

before_install:
  - sudo apt-get -y install libatspi2.0-dev
  - sudo apt-get -y install libatspi2.0-0
  - sudo apt-get -y install libdbus-1-dev
  - sudo apt-get -y install libglib2.0-dev
  

  