[package]
name = "tow"
version = "0.0.1"
edition = "2018"
keywords = ["xfce4", "xfwm4", "accessibility", "zoom", "ergonomy"]
authors = ["Luuk van der Duim <luukvanderduim@gmail.com>"]

[dependencies]
daemonize = "0.3"
glib-sys = "0.8"
gobject-sys = "0.8"
libc = "0.2"
libxdo = "0.6"
libxdo-sys = "0.11"
time = "0.1"
lazy_static = "1.2"
kahan = "0.1"
glib = "0.7"
gtypes = "0.2.0"

