[package]
name = "tow"
version = "0.0.1"
edition = "2018"
keywords = ["xfce4", "xfwm4", "accessibility", "zoom", "ergonomy", "accesibility", "a11y"]
authors = ["Luuk van der Duim <luukvanderduim@gmail.com>"]

[dependencies]
daemonize = "0.4"
glib-sys = "0.8"
gobject-sys = "0.8"
libc = "0.2"
glib = "0.7"
gtypes = "0.2"
xcb = "0.8"
clap = "2.9"
