[package]
name = "tow"
version = "0.0.1"
edition = "2018"
keywords = ["xfce4", "xfwm4", "accessibility", "a11y", "zoom", "ergonomy", "convenience"]
authors = ["Luuk van der Duim <luukvanderduim@gmail.com>"]

[dependencies]
daemonize = "0.4"
glib-sys = "0.9.0"
gobject-sys = "0.9.0"
libc = "0.2"
glib = "0.8.0"
gtypes = "0.2"
xcb = "0.8"
clap = "2.33"
rand ="0.7.0"
crossbeam-utils = "0.6.5"
